### ISSUE TITLE
VL/EID: Adding a readiness assessment checklist

### ISSUE THREAD

**Issue by mapesa** [APHLK/ePT-Repository#63]
1. How do you add a readiness assessment checklist?
2. How do you send it out to the participants?
3. How do you view the responses from the participants?

**Comment by brianvidosh** [comment]
The readiness checklist is there on both the participant menu and the admin menus. Something missing is the round field which is to tie the readiness to the round itself to avoid confusion. Am assuming they will have to setup the rounds in the system so that they can be tied to the checklist that is activated.
